apiVersion: v1
kind: Secret
metadata:
  name: federation
  namespace: cwa-server
type: Opaque
data:
  FEDERATION_GATEWAY_KEYSTORE_PASS: {{ .Values.federationPass | default "123456" | b64enc | quote }}
