apiVersion: batch/v1
kind: Job
metadata:
  name: objectstore-create-bucket
spec:
  template:
    spec:
      containers:
      - image: amazon/aws-cli
        env:
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.objectstore.accessKey | default ""  | quote }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.objectstore.secretKey | default "" | quote }}
        args: [ "s3api", "create-bucket", "--bucket", "cwa", "--endpoint-url", "http://objectstore:8000", "--acl", "public-read" ]
        imagePullPolicy: IfNotPresent
        name: objectstore-bucket-init
      restartPolicy: OnFailure