apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: objectstore
  namespace: cwa-server
data:
  CWA_OBJECTSTORE_ACCESSKEY: {{ .Values.objectstore.accessKey | default "" | b64enc | quote }}
  CWA_OBJECTSTORE_SECRETKEY: {{ .Values.objectstore.secretKey | default "" | b64enc | quote }}