apiVersion: v1
kind: Secret
metadata:
  name: postgres-upload
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_UPLOAD: {{ required "A pg.upload.password is required." .Values.pg.upload.password | b64enc | quote }}
  POSTGRESQL_USER_UPLOAD: {{ .Values.pg.upload.user | b64enc | quote }}
