apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/postgresql"
  claimRef:
    name: data-cwa-server-postgresql-0
    namespace: cwa-server
