apiVersion: v1
kind: Secret
metadata:
  name: postgres-callback
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_CALLBACK: {{ required "A pg.callback.password is required." .Values.pg.callback.password | b64enc | quote }}
  POSTGRESQL_USER_CALLBACK: {{ .Values.pg.callback.user | b64enc | quote }}
