apiVersion: v1
kind: Secret
metadata:
  name: postgres-flyway
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_FLYWAY: {{ required "A pg.flyway.password is required." .Values.pg.flyway.password | b64enc | quote }}
  POSTGRESQL_USER_FLYWAY: {{ .Values.pg.flyway.user | b64enc | quote }}
