apiVersion: v1
kind: Secret
metadata:
  name: postgres-distribution
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_DISTRIBUTION: {{ required "A pg.distribution.password is required." .Values.pg.distribution.password | b64enc | quote }}
  POSTGRESQL_USER_DISTRIBUTION: {{ .Values.pg.distribution.user | b64enc | quote }}
