apiVersion: v1
kind: Secret
metadata:
  name: postgres-submission
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_SUBMISSION: {{ required "A pg.submission.password is required." .Values.pg.submission.password | b64enc | quote }}
  POSTGRESQL_USER_SUBMISSION: {{ .Values.pg.submission.user | b64enc | quote }}

