apiVersion: v1
kind: Secret
metadata:
  name: postgres-download
  namespace: cwa-server
type: Opaque
data:
  POSTGRESQL_PASSWORD_DOWNLOAD: {{ required "A pg.download.password is required." .Values.pg.download.password | b64enc | quote }}
  POSTGRESQL_USER_DOWNLOAD: {{ .Values.pg.download.user | b64enc | quote }}
