apiVersion: v1
kind: Secret
metadata:
  name: postgres-init
  namespace: cwa-server
type: Opaque
data:
  1-setup-roles.sql: {{ .Values.pg.rolesScript | default "" | b64enc | quote }}
  2-create-users.sql: {{ tpl .Values.pg.usersScript . | default "" | b64enc | quote }}
