apiVersion: v1
kind: Secret
metadata:
  name: ssl
  namespace: cwa-server
type: Opaque
data:
  SSL_SUBMISSION_KEYSTORE_PASSWORD: {{ .Values.sslKeystorePassword | default "123456" | b64enc | quote }}
  SSL_VERIFICATION_TRUSTSTORE_PASSWORD: {{ .Values.sslKeystorePassword | default "123456" | b64enc | quote }}
  SSL_CALLBACK_KEYSTORE_PASSWORD: {{ .Values.sslKeystorePassword | default "123456" | b64enc | quote }}
  SSL_FEDERATION_TRUSTSTORE_PASSWORD: {{ .Values.sslFederationTruststorePassword | default "123456" | b64enc | quote }}
