{{- $service := "cwa-server-upload" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ $service }}
  name: {{ $service }}
  namespace: cwa-server
spec:
  schedule: {{ .Values.upload.schedule | default "0 * * * *" | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $service }}
        spec:
          containers:
            - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository $service .Chart.AppVersion | quote }}
              imagePullPolicy: IfNotPresent
              name: {{ $service }}
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: debug,disable-ssl-client-postgres,connect-efgs
              envFrom:
                - configMapRef:
                    name: vault-efgs
                - configMapRef:
                    name: federation
                - configMapRef:
                    name: postgres
                - configMapRef:
                    name: ssl
                - secretRef:
                    name: ssl
                - configMapRef:
                    name: federation
                - secretRef:
                    name: federation
                - secretRef:
                    name: postgres-upload
                - secretRef:
                    name: postgres-flyway
              volumeMounts:
                - name: secrets-volume
                  mountPath: /secrets
              # readinessProbe:
              #   httpGet:
              #     path: /health
              #     port: 8080
              #   periodSeconds: 10
          restartPolicy: OnFailure
          volumes:
            - name: secrets-volume
              secret:
                secretName: secret-files
status: {}